// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/agent.proto

package netctrlv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentStatus represents the current state of an agent
type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_ACTIVE      AgentStatus = 1
	AgentStatus_AGENT_STATUS_INACTIVE    AgentStatus = 2
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_ACTIVE",
		2: "AGENT_STATUS_INACTIVE",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"AGENT_STATUS_ACTIVE":      1,
		"AGENT_STATUS_INACTIVE":    2,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_v1_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{0}
}

// PortState represents the operational state of a NIC port
type PortState int32

const (
	PortState_PORT_STATE_UNSPECIFIED PortState = 0
	PortState_PORT_STATE_DOWN        PortState = 1
	PortState_PORT_STATE_UP          PortState = 2
	PortState_PORT_STATE_TESTING     PortState = 3
)

// Enum value maps for PortState.
var (
	PortState_name = map[int32]string{
		0: "PORT_STATE_UNSPECIFIED",
		1: "PORT_STATE_DOWN",
		2: "PORT_STATE_UP",
		3: "PORT_STATE_TESTING",
	}
	PortState_value = map[string]int32{
		"PORT_STATE_UNSPECIFIED": 0,
		"PORT_STATE_DOWN":        1,
		"PORT_STATE_UP":          2,
		"PORT_STATE_TESTING":     3,
	}
)

func (x PortState) Enum() *PortState {
	p := new(PortState)
	*p = x
	return p
}

func (x PortState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortState) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_proto_enumTypes[1].Descriptor()
}

func (PortState) Type() protoreflect.EnumType {
	return &file_v1_agent_proto_enumTypes[1]
}

func (x PortState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortState.Descriptor instead.
func (PortState) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{1}
}

// PortSpeed represents the link speed of a port
type PortSpeed int32

const (
	PortSpeed_PORT_SPEED_UNSPECIFIED PortSpeed = 0
	PortSpeed_PORT_SPEED_1G          PortSpeed = 1
	PortSpeed_PORT_SPEED_10G         PortSpeed = 10
	PortSpeed_PORT_SPEED_25G         PortSpeed = 25
	PortSpeed_PORT_SPEED_40G         PortSpeed = 40
	PortSpeed_PORT_SPEED_50G         PortSpeed = 50
	PortSpeed_PORT_SPEED_100G        PortSpeed = 100
	PortSpeed_PORT_SPEED_200G        PortSpeed = 200
	PortSpeed_PORT_SPEED_400G        PortSpeed = 400
)

// Enum value maps for PortSpeed.
var (
	PortSpeed_name = map[int32]string{
		0:   "PORT_SPEED_UNSPECIFIED",
		1:   "PORT_SPEED_1G",
		10:  "PORT_SPEED_10G",
		25:  "PORT_SPEED_25G",
		40:  "PORT_SPEED_40G",
		50:  "PORT_SPEED_50G",
		100: "PORT_SPEED_100G",
		200: "PORT_SPEED_200G",
		400: "PORT_SPEED_400G",
	}
	PortSpeed_value = map[string]int32{
		"PORT_SPEED_UNSPECIFIED": 0,
		"PORT_SPEED_1G":          1,
		"PORT_SPEED_10G":         10,
		"PORT_SPEED_25G":         25,
		"PORT_SPEED_40G":         40,
		"PORT_SPEED_50G":         50,
		"PORT_SPEED_100G":        100,
		"PORT_SPEED_200G":        200,
		"PORT_SPEED_400G":        400,
	}
)

func (x PortSpeed) Enum() *PortSpeed {
	p := new(PortSpeed)
	*p = x
	return p
}

func (x PortSpeed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortSpeed) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_proto_enumTypes[2].Descriptor()
}

func (PortSpeed) Type() protoreflect.EnumType {
	return &file_v1_agent_proto_enumTypes[2]
}

func (x PortSpeed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortSpeed.Descriptor instead.
func (PortSpeed) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{2}
}

// InstructionType defines the type of instruction
type InstructionType int32

const (
	InstructionType_INSTRUCTION_TYPE_UNSPECIFIED InstructionType = 0
	// POLL_INTERVAL instructs the agent when to poll next
	InstructionType_INSTRUCTION_TYPE_POLL_INTERVAL InstructionType = 1
	// HEALTH_CHECK requests a health status report
	InstructionType_INSTRUCTION_TYPE_HEALTH_CHECK InstructionType = 2
	// COLLECT_HARDWARE requests hardware inventory (Mellanox NICs)
	InstructionType_INSTRUCTION_TYPE_COLLECT_HARDWARE InstructionType = 3
)

// Enum value maps for InstructionType.
var (
	InstructionType_name = map[int32]string{
		0: "INSTRUCTION_TYPE_UNSPECIFIED",
		1: "INSTRUCTION_TYPE_POLL_INTERVAL",
		2: "INSTRUCTION_TYPE_HEALTH_CHECK",
		3: "INSTRUCTION_TYPE_COLLECT_HARDWARE",
	}
	InstructionType_value = map[string]int32{
		"INSTRUCTION_TYPE_UNSPECIFIED":      0,
		"INSTRUCTION_TYPE_POLL_INTERVAL":    1,
		"INSTRUCTION_TYPE_HEALTH_CHECK":     2,
		"INSTRUCTION_TYPE_COLLECT_HARDWARE": 3,
	}
)

func (x InstructionType) Enum() *InstructionType {
	p := new(InstructionType)
	*p = x
	return p
}

func (x InstructionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstructionType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_proto_enumTypes[3].Descriptor()
}

func (InstructionType) Type() protoreflect.EnumType {
	return &file_v1_agent_proto_enumTypes[3]
}

func (x InstructionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstructionType.Descriptor instead.
func (InstructionType) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{3}
}

// MellanoxPort represents a single port on a Mellanox NIC
type MellanoxPort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Port number (1-based)
	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// Port state (up/down)
	State PortState `protobuf:"varint,2,opt,name=state,proto3,enum=netctrl.v1.PortState" json:"state,omitempty"`
	// Link speed in Gbps
	Speed PortSpeed `protobuf:"varint,3,opt,name=speed,proto3,enum=netctrl.v1.PortSpeed" json:"speed,omitempty"`
	// MAC address
	MacAddress string `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	// MTU size
	Mtu int32 `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Port GUID
	Guid string `protobuf:"bytes,6,opt,name=guid,proto3" json:"guid,omitempty"`
	// PCI address for this port (e.g., "0000:03:00.1")
	PciAddress string `protobuf:"bytes,7,opt,name=pci_address,json=pciAddress,proto3" json:"pci_address,omitempty"`
	// Network interface name (e.g., "ens1f0")
	InterfaceName string `protobuf:"bytes,8,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MellanoxPort) Reset() {
	*x = MellanoxPort{}
	mi := &file_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MellanoxPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MellanoxPort) ProtoMessage() {}

func (x *MellanoxPort) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MellanoxPort.ProtoReflect.Descriptor instead.
func (*MellanoxPort) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *MellanoxPort) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *MellanoxPort) GetState() PortState {
	if x != nil {
		return x.State
	}
	return PortState_PORT_STATE_UNSPECIFIED
}

func (x *MellanoxPort) GetSpeed() PortSpeed {
	if x != nil {
		return x.Speed
	}
	return PortSpeed_PORT_SPEED_UNSPECIFIED
}

func (x *MellanoxPort) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *MellanoxPort) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *MellanoxPort) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *MellanoxPort) GetPciAddress() string {
	if x != nil {
		return x.PciAddress
	}
	return ""
}

func (x *MellanoxPort) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

// MellanoxNIC represents a Mellanox network interface card
type MellanoxNIC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device name (e.g., "mlx5_0")
	DeviceName string `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// PCI address (e.g., "0000:03:00.0")
	PciAddress string `protobuf:"bytes,2,opt,name=pci_address,json=pciAddress,proto3" json:"pci_address,omitempty"`
	// Part number / model
	PartNumber string `protobuf:"bytes,3,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	// Serial number
	SerialNumber string `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	// Firmware version
	FirmwareVersion string `protobuf:"bytes,5,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	// Number of ports on this NIC
	PortCount int32 `protobuf:"varint,6,opt,name=port_count,json=portCount,proto3" json:"port_count,omitempty"`
	// Port details
	Ports []*MellanoxPort `protobuf:"bytes,7,rep,name=ports,proto3" json:"ports,omitempty"`
	// PSID (Parameter Set ID)
	Psid          string `protobuf:"bytes,8,opt,name=psid,proto3" json:"psid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MellanoxNIC) Reset() {
	*x = MellanoxNIC{}
	mi := &file_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MellanoxNIC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MellanoxNIC) ProtoMessage() {}

func (x *MellanoxNIC) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MellanoxNIC.ProtoReflect.Descriptor instead.
func (*MellanoxNIC) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *MellanoxNIC) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *MellanoxNIC) GetPciAddress() string {
	if x != nil {
		return x.PciAddress
	}
	return ""
}

func (x *MellanoxNIC) GetPartNumber() string {
	if x != nil {
		return x.PartNumber
	}
	return ""
}

func (x *MellanoxNIC) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *MellanoxNIC) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *MellanoxNIC) GetPortCount() int32 {
	if x != nil {
		return x.PortCount
	}
	return 0
}

func (x *MellanoxNIC) GetPorts() []*MellanoxPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *MellanoxNIC) GetPsid() string {
	if x != nil {
		return x.Psid
	}
	return ""
}

// Agent represents a node agent registered to a cluster
type Agent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent-generated UUID (hardware-based identifier)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Cluster ID this agent belongs to
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Node hostname
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Node IP address
	IpAddress string `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Agent version
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Agent status
	Status AgentStatus `protobuf:"varint,6,opt,name=status,proto3,enum=netctrl.v1.AgentStatus" json:"status,omitempty"`
	// Last registration or update time
	LastSeen *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Mellanox NICs reported by agent (populated via hardware collection instruction)
	NetworkInterfaces []*MellanoxNIC `protobuf:"bytes,10,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	// Whether hardware collection has been completed (true even if no NICs found)
	HardwareCollected bool `protobuf:"varint,11,opt,name=hardware_collected,json=hardwareCollected,proto3" json:"hardware_collected,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Agent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Agent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Agent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Agent) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *Agent) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Agent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Agent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Agent) GetNetworkInterfaces() []*MellanoxNIC {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *Agent) GetHardwareCollected() bool {
	if x != nil {
		return x.HardwareCollected
	}
	return false
}

// RegisterAgentRequest contains parameters for registering an agent
type RegisterAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent-generated UUID (required)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Cluster ID (required)
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Node hostname (optional)
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Node IP address (optional)
	IpAddress string `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Agent version (optional)
	Version       string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterAgentRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RegisterAgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterAgentRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterAgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// RegisterAgentResponse returns the registered agent
type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// GetAgentRequest contains parameters for retrieving an agent
type GetAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the agent to retrieve
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetAgentResponse returns the requested agent
type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// ListAgentsRequest contains parameters for listing agents
type ListAgentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional cluster ID filter
	ClusterId     string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListAgentsRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// ListAgentsResponse returns a list of agents
type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

// UnregisterAgentRequest contains parameters for unregistering an agent
type UnregisterAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the agent to unregister
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentRequest) Reset() {
	*x = UnregisterAgentRequest{}
	mi := &file_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentRequest) ProtoMessage() {}

func (x *UnregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*UnregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *UnregisterAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UnregisterAgentResponse confirms unregistration
type UnregisterAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the unregistration was successful
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentResponse) Reset() {
	*x = UnregisterAgentResponse{}
	mi := &file_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentResponse) ProtoMessage() {}

func (x *UnregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*UnregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *UnregisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Instruction represents a command or directive from the service to an agent
type Instruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique instruction ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type of instruction
	Type InstructionType `protobuf:"varint,2,opt,name=type,proto3,enum=netctrl.v1.InstructionType" json:"type,omitempty"`
	// Instruction payload (type-specific data as JSON)
	Payload string `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// When the instruction was created
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *Instruction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instruction) GetType() InstructionType {
	if x != nil {
		return x.Type
	}
	return InstructionType_INSTRUCTION_TYPE_UNSPECIFIED
}

func (x *Instruction) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Instruction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// HardwareCollectionResult contains the result of hardware collection
type HardwareCollectionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Collected Mellanox NICs
	NetworkInterfaces []*MellanoxNIC `protobuf:"bytes,1,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HardwareCollectionResult) Reset() {
	*x = HardwareCollectionResult{}
	mi := &file_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareCollectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareCollectionResult) ProtoMessage() {}

func (x *HardwareCollectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareCollectionResult.ProtoReflect.Descriptor instead.
func (*HardwareCollectionResult) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *HardwareCollectionResult) GetNetworkInterfaces() []*MellanoxNIC {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

// HealthCheckResult contains the result of a health check
type HealthCheckResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Health status
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Optional error message if unhealthy
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResult) Reset() {
	*x = HealthCheckResult{}
	mi := &file_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResult) ProtoMessage() {}

func (x *HealthCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResult.ProtoReflect.Descriptor instead.
func (*HealthCheckResult) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckResult) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// InstructionResult represents the result of executing an instruction
type InstructionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of instruction that was executed
	InstructionType InstructionType `protobuf:"varint,1,opt,name=instruction_type,json=instructionType,proto3,enum=netctrl.v1.InstructionType" json:"instruction_type,omitempty"`
	// Type-specific result data
	//
	// Types that are valid to be assigned to Result:
	//
	//	*InstructionResult_HardwareCollection
	//	*InstructionResult_HealthCheck
	Result        isInstructionResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructionResult) Reset() {
	*x = InstructionResult{}
	mi := &file_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructionResult) ProtoMessage() {}

func (x *InstructionResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructionResult.ProtoReflect.Descriptor instead.
func (*InstructionResult) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *InstructionResult) GetInstructionType() InstructionType {
	if x != nil {
		return x.InstructionType
	}
	return InstructionType_INSTRUCTION_TYPE_UNSPECIFIED
}

func (x *InstructionResult) GetResult() isInstructionResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InstructionResult) GetHardwareCollection() *HardwareCollectionResult {
	if x != nil {
		if x, ok := x.Result.(*InstructionResult_HardwareCollection); ok {
			return x.HardwareCollection
		}
	}
	return nil
}

func (x *InstructionResult) GetHealthCheck() *HealthCheckResult {
	if x != nil {
		if x, ok := x.Result.(*InstructionResult_HealthCheck); ok {
			return x.HealthCheck
		}
	}
	return nil
}

type isInstructionResult_Result interface {
	isInstructionResult_Result()
}

type InstructionResult_HardwareCollection struct {
	HardwareCollection *HardwareCollectionResult `protobuf:"bytes,2,opt,name=hardware_collection,json=hardwareCollection,proto3,oneof"`
}

type InstructionResult_HealthCheck struct {
	HealthCheck *HealthCheckResult `protobuf:"bytes,3,opt,name=health_check,json=healthCheck,proto3,oneof"` // Future result types can be added here
}

func (*InstructionResult_HardwareCollection) isInstructionResult_Result() {}

func (*InstructionResult_HealthCheck) isInstructionResult_Result() {}

// GetInstructionsRequest requests pending instructions for an agent
type GetInstructionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the agent requesting instructions
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Optional: ID of the last successfully processed instruction (acknowledgment)
	LastInstructionId string `protobuf:"bytes,2,opt,name=last_instruction_id,json=lastInstructionId,proto3" json:"last_instruction_id,omitempty"`
	// Optional: Result from the last instruction execution
	Result        *InstructionResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstructionsRequest) Reset() {
	*x = GetInstructionsRequest{}
	mi := &file_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstructionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstructionsRequest) ProtoMessage() {}

func (x *GetInstructionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstructionsRequest.ProtoReflect.Descriptor instead.
func (*GetInstructionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *GetInstructionsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetInstructionsRequest) GetLastInstructionId() string {
	if x != nil {
		return x.LastInstructionId
	}
	return ""
}

func (x *GetInstructionsRequest) GetResult() *InstructionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// GetInstructionsResponse returns instructions and polling configuration
type GetInstructionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of pending instructions to execute
	Instructions []*Instruction `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	// Seconds to wait before the next poll
	// Default behavior: agent should poll after this interval
	PollIntervalSeconds int32 `protobuf:"varint,2,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3" json:"poll_interval_seconds,omitempty"`
	// Server timestamp when response was generated
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstructionsResponse) Reset() {
	*x = GetInstructionsResponse{}
	mi := &file_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstructionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstructionsResponse) ProtoMessage() {}

func (x *GetInstructionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstructionsResponse.ProtoReflect.Descriptor instead.
func (*GetInstructionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *GetInstructionsResponse) GetInstructions() []*Instruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *GetInstructionsResponse) GetPollIntervalSeconds() int32 {
	if x != nil {
		return x.PollIntervalSeconds
	}
	return 0
}

func (x *GetInstructionsResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

var File_v1_agent_proto protoreflect.FileDescriptor

const file_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/agent.proto\x12\n" +
	"netctrl.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x02\n" +
	"\fMellanoxPort\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12+\n" +
	"\x05state\x18\x02 \x01(\x0e2\x15.netctrl.v1.PortStateR\x05state\x12+\n" +
	"\x05speed\x18\x03 \x01(\x0e2\x15.netctrl.v1.PortSpeedR\x05speed\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\x12\x10\n" +
	"\x03mtu\x18\x05 \x01(\x05R\x03mtu\x12\x12\n" +
	"\x04guid\x18\x06 \x01(\tR\x04guid\x12\x1f\n" +
	"\vpci_address\x18\a \x01(\tR\n" +
	"pciAddress\x12%\n" +
	"\x0einterface_name\x18\b \x01(\tR\rinterfaceName\"\xa3\x02\n" +
	"\vMellanoxNIC\x12\x1f\n" +
	"\vdevice_name\x18\x01 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vpci_address\x18\x02 \x01(\tR\n" +
	"pciAddress\x12\x1f\n" +
	"\vpart_number\x18\x03 \x01(\tR\n" +
	"partNumber\x12#\n" +
	"\rserial_number\x18\x04 \x01(\tR\fserialNumber\x12)\n" +
	"\x10firmware_version\x18\x05 \x01(\tR\x0ffirmwareVersion\x12\x1d\n" +
	"\n" +
	"port_count\x18\x06 \x01(\x05R\tportCount\x12.\n" +
	"\x05ports\x18\a \x03(\v2\x18.netctrl.v1.MellanoxPortR\x05ports\x12\x12\n" +
	"\x04psid\x18\b \x01(\tR\x04psid\"\xe2\x03\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12/\n" +
	"\x06status\x18\x06 \x01(\x0e2\x17.netctrl.v1.AgentStatusR\x06status\x127\n" +
	"\tlast_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12F\n" +
	"\x12network_interfaces\x18\n" +
	" \x03(\v2\x17.netctrl.v1.MellanoxNICR\x11networkInterfaces\x12-\n" +
	"\x12hardware_collected\x18\v \x01(\bR\x11hardwareCollected\"\x9a\x01\n" +
	"\x14RegisterAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"@\n" +
	"\x15RegisterAgentResponse\x12'\n" +
	"\x05agent\x18\x01 \x01(\v2\x11.netctrl.v1.AgentR\x05agent\"!\n" +
	"\x0fGetAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x10GetAgentResponse\x12'\n" +
	"\x05agent\x18\x01 \x01(\v2\x11.netctrl.v1.AgentR\x05agent\"2\n" +
	"\x11ListAgentsRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"?\n" +
	"\x12ListAgentsResponse\x12)\n" +
	"\x06agents\x18\x01 \x03(\v2\x11.netctrl.v1.AgentR\x06agents\"(\n" +
	"\x16UnregisterAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17UnregisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa3\x01\n" +
	"\vInstruction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.netctrl.v1.InstructionTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"b\n" +
	"\x18HardwareCollectionResult\x12F\n" +
	"\x12network_interfaces\x18\x01 \x03(\v2\x17.netctrl.v1.MellanoxNICR\x11networkInterfaces\"R\n" +
	"\x11HealthCheckResult\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x82\x02\n" +
	"\x11InstructionResult\x12F\n" +
	"\x10instruction_type\x18\x01 \x01(\x0e2\x1b.netctrl.v1.InstructionTypeR\x0finstructionType\x12W\n" +
	"\x13hardware_collection\x18\x02 \x01(\v2$.netctrl.v1.HardwareCollectionResultH\x00R\x12hardwareCollection\x12B\n" +
	"\fhealth_check\x18\x03 \x01(\v2\x1d.netctrl.v1.HealthCheckResultH\x00R\vhealthCheckB\b\n" +
	"\x06result\"\x9a\x01\n" +
	"\x16GetInstructionsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12.\n" +
	"\x13last_instruction_id\x18\x02 \x01(\tR\x11lastInstructionId\x125\n" +
	"\x06result\x18\x03 \x01(\v2\x1d.netctrl.v1.InstructionResultR\x06result\"\xc7\x01\n" +
	"\x17GetInstructionsResponse\x12;\n" +
	"\finstructions\x18\x01 \x03(\v2\x17.netctrl.v1.InstructionR\finstructions\x122\n" +
	"\x15poll_interval_seconds\x18\x02 \x01(\x05R\x13pollIntervalSeconds\x12;\n" +
	"\vserver_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime*_\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13AGENT_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15AGENT_STATUS_INACTIVE\x10\x02*g\n" +
	"\tPortState\x12\x1a\n" +
	"\x16PORT_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPORT_STATE_DOWN\x10\x01\x12\x11\n" +
	"\rPORT_STATE_UP\x10\x02\x12\x16\n" +
	"\x12PORT_STATE_TESTING\x10\x03*\xcb\x01\n" +
	"\tPortSpeed\x12\x1a\n" +
	"\x16PORT_SPEED_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPORT_SPEED_1G\x10\x01\x12\x12\n" +
	"\x0ePORT_SPEED_10G\x10\n" +
	"\x12\x12\n" +
	"\x0ePORT_SPEED_25G\x10\x19\x12\x12\n" +
	"\x0ePORT_SPEED_40G\x10(\x12\x12\n" +
	"\x0ePORT_SPEED_50G\x102\x12\x13\n" +
	"\x0fPORT_SPEED_100G\x10d\x12\x14\n" +
	"\x0fPORT_SPEED_200G\x10\xc8\x01\x12\x14\n" +
	"\x0fPORT_SPEED_400G\x10\x90\x03*\xa1\x01\n" +
	"\x0fInstructionType\x12 \n" +
	"\x1cINSTRUCTION_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eINSTRUCTION_TYPE_POLL_INTERVAL\x10\x01\x12!\n" +
	"\x1dINSTRUCTION_TYPE_HEALTH_CHECK\x10\x02\x12%\n" +
	"!INSTRUCTION_TYPE_COLLECT_HARDWARE\x10\x032\xda\x04\n" +
	"\fAgentService\x12x\n" +
	"\rRegisterAgent\x12 .netctrl.v1.RegisterAgentRequest\x1a!.netctrl.v1.RegisterAgentResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/agents/register\x12b\n" +
	"\bGetAgent\x12\x1b.netctrl.v1.GetAgentRequest\x1a\x1c.netctrl.v1.GetAgentResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/agents/{id}\x12c\n" +
	"\n" +
	"ListAgents\x12\x1d.netctrl.v1.ListAgentsRequest\x1a\x1e.netctrl.v1.ListAgentsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/agents\x12w\n" +
	"\x0fUnregisterAgent\x12\".netctrl.v1.UnregisterAgentRequest\x1a#.netctrl.v1.UnregisterAgentResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/v1/agents/{id}\x12\x8d\x01\n" +
	"\x0fGetInstructions\x12\".netctrl.v1.GetInstructionsRequest\x1a#.netctrl.v1.GetInstructionsResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/agents/{agent_id}/instructionsB\x9d\x01\n" +
	"\x0ecom.netctrl.v1B\n" +
	"AgentProtoP\x01Z6github.com/filanov/netctrl-server/pkg/api/v1;netctrlv1\xa2\x02\x03NXX\xaa\x02\n" +
	"Netctrl.V1\xca\x02\n" +
	"Netctrl\\V1\xe2\x02\x16Netctrl\\V1\\GPBMetadata\xea\x02\vNetctrl::V1b\x06proto3"

var (
	file_v1_agent_proto_rawDescOnce sync.Once
	file_v1_agent_proto_rawDescData []byte
)

func file_v1_agent_proto_rawDescGZIP() []byte {
	file_v1_agent_proto_rawDescOnce.Do(func() {
		file_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_agent_proto_rawDesc), len(file_v1_agent_proto_rawDesc)))
	})
	return file_v1_agent_proto_rawDescData
}

var file_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_v1_agent_proto_goTypes = []any{
	(AgentStatus)(0),                 // 0: netctrl.v1.AgentStatus
	(PortState)(0),                   // 1: netctrl.v1.PortState
	(PortSpeed)(0),                   // 2: netctrl.v1.PortSpeed
	(InstructionType)(0),             // 3: netctrl.v1.InstructionType
	(*MellanoxPort)(nil),             // 4: netctrl.v1.MellanoxPort
	(*MellanoxNIC)(nil),              // 5: netctrl.v1.MellanoxNIC
	(*Agent)(nil),                    // 6: netctrl.v1.Agent
	(*RegisterAgentRequest)(nil),     // 7: netctrl.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),    // 8: netctrl.v1.RegisterAgentResponse
	(*GetAgentRequest)(nil),          // 9: netctrl.v1.GetAgentRequest
	(*GetAgentResponse)(nil),         // 10: netctrl.v1.GetAgentResponse
	(*ListAgentsRequest)(nil),        // 11: netctrl.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),       // 12: netctrl.v1.ListAgentsResponse
	(*UnregisterAgentRequest)(nil),   // 13: netctrl.v1.UnregisterAgentRequest
	(*UnregisterAgentResponse)(nil),  // 14: netctrl.v1.UnregisterAgentResponse
	(*Instruction)(nil),              // 15: netctrl.v1.Instruction
	(*HardwareCollectionResult)(nil), // 16: netctrl.v1.HardwareCollectionResult
	(*HealthCheckResult)(nil),        // 17: netctrl.v1.HealthCheckResult
	(*InstructionResult)(nil),        // 18: netctrl.v1.InstructionResult
	(*GetInstructionsRequest)(nil),   // 19: netctrl.v1.GetInstructionsRequest
	(*GetInstructionsResponse)(nil),  // 20: netctrl.v1.GetInstructionsResponse
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
}
var file_v1_agent_proto_depIdxs = []int32{
	1,  // 0: netctrl.v1.MellanoxPort.state:type_name -> netctrl.v1.PortState
	2,  // 1: netctrl.v1.MellanoxPort.speed:type_name -> netctrl.v1.PortSpeed
	4,  // 2: netctrl.v1.MellanoxNIC.ports:type_name -> netctrl.v1.MellanoxPort
	0,  // 3: netctrl.v1.Agent.status:type_name -> netctrl.v1.AgentStatus
	21, // 4: netctrl.v1.Agent.last_seen:type_name -> google.protobuf.Timestamp
	21, // 5: netctrl.v1.Agent.created_at:type_name -> google.protobuf.Timestamp
	21, // 6: netctrl.v1.Agent.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 7: netctrl.v1.Agent.network_interfaces:type_name -> netctrl.v1.MellanoxNIC
	6,  // 8: netctrl.v1.RegisterAgentResponse.agent:type_name -> netctrl.v1.Agent
	6,  // 9: netctrl.v1.GetAgentResponse.agent:type_name -> netctrl.v1.Agent
	6,  // 10: netctrl.v1.ListAgentsResponse.agents:type_name -> netctrl.v1.Agent
	3,  // 11: netctrl.v1.Instruction.type:type_name -> netctrl.v1.InstructionType
	21, // 12: netctrl.v1.Instruction.created_at:type_name -> google.protobuf.Timestamp
	5,  // 13: netctrl.v1.HardwareCollectionResult.network_interfaces:type_name -> netctrl.v1.MellanoxNIC
	3,  // 14: netctrl.v1.InstructionResult.instruction_type:type_name -> netctrl.v1.InstructionType
	16, // 15: netctrl.v1.InstructionResult.hardware_collection:type_name -> netctrl.v1.HardwareCollectionResult
	17, // 16: netctrl.v1.InstructionResult.health_check:type_name -> netctrl.v1.HealthCheckResult
	18, // 17: netctrl.v1.GetInstructionsRequest.result:type_name -> netctrl.v1.InstructionResult
	15, // 18: netctrl.v1.GetInstructionsResponse.instructions:type_name -> netctrl.v1.Instruction
	21, // 19: netctrl.v1.GetInstructionsResponse.server_time:type_name -> google.protobuf.Timestamp
	7,  // 20: netctrl.v1.AgentService.RegisterAgent:input_type -> netctrl.v1.RegisterAgentRequest
	9,  // 21: netctrl.v1.AgentService.GetAgent:input_type -> netctrl.v1.GetAgentRequest
	11, // 22: netctrl.v1.AgentService.ListAgents:input_type -> netctrl.v1.ListAgentsRequest
	13, // 23: netctrl.v1.AgentService.UnregisterAgent:input_type -> netctrl.v1.UnregisterAgentRequest
	19, // 24: netctrl.v1.AgentService.GetInstructions:input_type -> netctrl.v1.GetInstructionsRequest
	8,  // 25: netctrl.v1.AgentService.RegisterAgent:output_type -> netctrl.v1.RegisterAgentResponse
	10, // 26: netctrl.v1.AgentService.GetAgent:output_type -> netctrl.v1.GetAgentResponse
	12, // 27: netctrl.v1.AgentService.ListAgents:output_type -> netctrl.v1.ListAgentsResponse
	14, // 28: netctrl.v1.AgentService.UnregisterAgent:output_type -> netctrl.v1.UnregisterAgentResponse
	20, // 29: netctrl.v1.AgentService.GetInstructions:output_type -> netctrl.v1.GetInstructionsResponse
	25, // [25:30] is the sub-list for method output_type
	20, // [20:25] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_v1_agent_proto_init() }
func file_v1_agent_proto_init() {
	if File_v1_agent_proto != nil {
		return
	}
	file_v1_agent_proto_msgTypes[14].OneofWrappers = []any{
		(*InstructionResult_HardwareCollection)(nil),
		(*InstructionResult_HealthCheck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_agent_proto_rawDesc), len(file_v1_agent_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_agent_proto_goTypes,
		DependencyIndexes: file_v1_agent_proto_depIdxs,
		EnumInfos:         file_v1_agent_proto_enumTypes,
		MessageInfos:      file_v1_agent_proto_msgTypes,
	}.Build()
	File_v1_agent_proto = out.File
	file_v1_agent_proto_goTypes = nil
	file_v1_agent_proto_depIdxs = nil
}
