// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/agent.proto

package netctrlv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentStatus represents the current state of an agent
type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_ACTIVE      AgentStatus = 1
	AgentStatus_AGENT_STATUS_INACTIVE    AgentStatus = 2
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_ACTIVE",
		2: "AGENT_STATUS_INACTIVE",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"AGENT_STATUS_ACTIVE":      1,
		"AGENT_STATUS_INACTIVE":    2,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_v1_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{0}
}

// Agent represents a node agent registered to a cluster
type Agent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent-generated UUID (hardware-based identifier)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Cluster ID this agent belongs to
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Node hostname
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Node IP address
	IpAddress string `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Agent version
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Agent status
	Status AgentStatus `protobuf:"varint,6,opt,name=status,proto3,enum=netctrl.v1.AgentStatus" json:"status,omitempty"`
	// Last registration or update time
	LastSeen *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Agent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Agent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Agent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Agent) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *Agent) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Agent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Agent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// RegisterAgentRequest contains parameters for registering an agent
type RegisterAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent-generated UUID (required)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Cluster ID (required)
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Node hostname (optional)
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Node IP address (optional)
	IpAddress string `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Agent version (optional)
	Version       string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterAgentRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RegisterAgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterAgentRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterAgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// RegisterAgentResponse returns the registered agent
type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// GetAgentRequest contains parameters for retrieving an agent
type GetAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the agent to retrieve
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetAgentResponse returns the requested agent
type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// ListAgentsRequest contains parameters for listing agents
type ListAgentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional cluster ID filter
	ClusterId     string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListAgentsRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// ListAgentsResponse returns a list of agents
type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

// UnregisterAgentRequest contains parameters for unregistering an agent
type UnregisterAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the agent to unregister
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentRequest) Reset() {
	*x = UnregisterAgentRequest{}
	mi := &file_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentRequest) ProtoMessage() {}

func (x *UnregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*UnregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UnregisterAgentResponse confirms unregistration
type UnregisterAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the unregistration was successful
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentResponse) Reset() {
	*x = UnregisterAgentResponse{}
	mi := &file_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentResponse) ProtoMessage() {}

func (x *UnregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*UnregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *UnregisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_v1_agent_proto protoreflect.FileDescriptor

const file_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/agent.proto\x12\n" +
	"netctrl.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x02\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12/\n" +
	"\x06status\x18\x06 \x01(\x0e2\x17.netctrl.v1.AgentStatusR\x06status\x127\n" +
	"\tlast_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9a\x01\n" +
	"\x14RegisterAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"@\n" +
	"\x15RegisterAgentResponse\x12'\n" +
	"\x05agent\x18\x01 \x01(\v2\x11.netctrl.v1.AgentR\x05agent\"!\n" +
	"\x0fGetAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x10GetAgentResponse\x12'\n" +
	"\x05agent\x18\x01 \x01(\v2\x11.netctrl.v1.AgentR\x05agent\"2\n" +
	"\x11ListAgentsRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"?\n" +
	"\x12ListAgentsResponse\x12)\n" +
	"\x06agents\x18\x01 \x03(\v2\x11.netctrl.v1.AgentR\x06agents\"(\n" +
	"\x16UnregisterAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17UnregisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*_\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13AGENT_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15AGENT_STATUS_INACTIVE\x10\x022\xca\x03\n" +
	"\fAgentService\x12x\n" +
	"\rRegisterAgent\x12 .netctrl.v1.RegisterAgentRequest\x1a!.netctrl.v1.RegisterAgentResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/agents/register\x12b\n" +
	"\bGetAgent\x12\x1b.netctrl.v1.GetAgentRequest\x1a\x1c.netctrl.v1.GetAgentResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/agents/{id}\x12c\n" +
	"\n" +
	"ListAgents\x12\x1d.netctrl.v1.ListAgentsRequest\x1a\x1e.netctrl.v1.ListAgentsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/agents\x12w\n" +
	"\x0fUnregisterAgent\x12\".netctrl.v1.UnregisterAgentRequest\x1a#.netctrl.v1.UnregisterAgentResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/v1/agents/{id}B\x9d\x01\n" +
	"\x0ecom.netctrl.v1B\n" +
	"AgentProtoP\x01Z6github.com/filanov/netctrl-server/pkg/api/v1;netctrlv1\xa2\x02\x03NXX\xaa\x02\n" +
	"Netctrl.V1\xca\x02\n" +
	"Netctrl\\V1\xe2\x02\x16Netctrl\\V1\\GPBMetadata\xea\x02\vNetctrl::V1b\x06proto3"

var (
	file_v1_agent_proto_rawDescOnce sync.Once
	file_v1_agent_proto_rawDescData []byte
)

func file_v1_agent_proto_rawDescGZIP() []byte {
	file_v1_agent_proto_rawDescOnce.Do(func() {
		file_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_agent_proto_rawDesc), len(file_v1_agent_proto_rawDesc)))
	})
	return file_v1_agent_proto_rawDescData
}

var file_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_agent_proto_goTypes = []any{
	(AgentStatus)(0),                // 0: netctrl.v1.AgentStatus
	(*Agent)(nil),                   // 1: netctrl.v1.Agent
	(*RegisterAgentRequest)(nil),    // 2: netctrl.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),   // 3: netctrl.v1.RegisterAgentResponse
	(*GetAgentRequest)(nil),         // 4: netctrl.v1.GetAgentRequest
	(*GetAgentResponse)(nil),        // 5: netctrl.v1.GetAgentResponse
	(*ListAgentsRequest)(nil),       // 6: netctrl.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),      // 7: netctrl.v1.ListAgentsResponse
	(*UnregisterAgentRequest)(nil),  // 8: netctrl.v1.UnregisterAgentRequest
	(*UnregisterAgentResponse)(nil), // 9: netctrl.v1.UnregisterAgentResponse
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
}
var file_v1_agent_proto_depIdxs = []int32{
	0,  // 0: netctrl.v1.Agent.status:type_name -> netctrl.v1.AgentStatus
	10, // 1: netctrl.v1.Agent.last_seen:type_name -> google.protobuf.Timestamp
	10, // 2: netctrl.v1.Agent.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: netctrl.v1.Agent.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: netctrl.v1.RegisterAgentResponse.agent:type_name -> netctrl.v1.Agent
	1,  // 5: netctrl.v1.GetAgentResponse.agent:type_name -> netctrl.v1.Agent
	1,  // 6: netctrl.v1.ListAgentsResponse.agents:type_name -> netctrl.v1.Agent
	2,  // 7: netctrl.v1.AgentService.RegisterAgent:input_type -> netctrl.v1.RegisterAgentRequest
	4,  // 8: netctrl.v1.AgentService.GetAgent:input_type -> netctrl.v1.GetAgentRequest
	6,  // 9: netctrl.v1.AgentService.ListAgents:input_type -> netctrl.v1.ListAgentsRequest
	8,  // 10: netctrl.v1.AgentService.UnregisterAgent:input_type -> netctrl.v1.UnregisterAgentRequest
	3,  // 11: netctrl.v1.AgentService.RegisterAgent:output_type -> netctrl.v1.RegisterAgentResponse
	5,  // 12: netctrl.v1.AgentService.GetAgent:output_type -> netctrl.v1.GetAgentResponse
	7,  // 13: netctrl.v1.AgentService.ListAgents:output_type -> netctrl.v1.ListAgentsResponse
	9,  // 14: netctrl.v1.AgentService.UnregisterAgent:output_type -> netctrl.v1.UnregisterAgentResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_v1_agent_proto_init() }
func file_v1_agent_proto_init() {
	if File_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_agent_proto_rawDesc), len(file_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_agent_proto_goTypes,
		DependencyIndexes: file_v1_agent_proto_depIdxs,
		EnumInfos:         file_v1_agent_proto_enumTypes,
		MessageInfos:      file_v1_agent_proto_msgTypes,
	}.Build()
	File_v1_agent_proto = out.File
	file_v1_agent_proto_goTypes = nil
	file_v1_agent_proto_depIdxs = nil
}
