// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/health.proto

package netctrlv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthStatus represents the health state of the service
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_UNHEALTHY":   2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_health_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_v1_health_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_health_proto_rawDescGZIP(), []int{0}
}

// ReadinessStatus represents the readiness state of the service
type ReadinessStatus int32

const (
	ReadinessStatus_READINESS_STATUS_UNSPECIFIED ReadinessStatus = 0
	ReadinessStatus_READINESS_STATUS_READY       ReadinessStatus = 1
	ReadinessStatus_READINESS_STATUS_NOT_READY   ReadinessStatus = 2
)

// Enum value maps for ReadinessStatus.
var (
	ReadinessStatus_name = map[int32]string{
		0: "READINESS_STATUS_UNSPECIFIED",
		1: "READINESS_STATUS_READY",
		2: "READINESS_STATUS_NOT_READY",
	}
	ReadinessStatus_value = map[string]int32{
		"READINESS_STATUS_UNSPECIFIED": 0,
		"READINESS_STATUS_READY":       1,
		"READINESS_STATUS_NOT_READY":   2,
	}
)

func (x ReadinessStatus) Enum() *ReadinessStatus {
	p := new(ReadinessStatus)
	*p = x
	return p
}

func (x ReadinessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadinessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_health_proto_enumTypes[1].Descriptor()
}

func (ReadinessStatus) Type() protoreflect.EnumType {
	return &file_v1_health_proto_enumTypes[1]
}

func (x ReadinessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadinessStatus.Descriptor instead.
func (ReadinessStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_health_proto_rawDescGZIP(), []int{1}
}

// HealthCheckRequest is the request for health checks
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_v1_health_proto_rawDescGZIP(), []int{0}
}

// HealthCheckResponse contains health status information
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall health status
	Status HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=netctrl.v1.HealthStatus" json:"status,omitempty"`
	// Optional message providing additional context
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ReadinessCheckRequest is the request for readiness checks
type ReadinessCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessCheckRequest) Reset() {
	*x = ReadinessCheckRequest{}
	mi := &file_v1_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessCheckRequest) ProtoMessage() {}

func (x *ReadinessCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessCheckRequest.ProtoReflect.Descriptor instead.
func (*ReadinessCheckRequest) Descriptor() ([]byte, []int) {
	return file_v1_health_proto_rawDescGZIP(), []int{2}
}

// ReadinessCheckResponse contains readiness status information
type ReadinessCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall readiness status
	Status ReadinessStatus `protobuf:"varint,1,opt,name=status,proto3,enum=netctrl.v1.ReadinessStatus" json:"status,omitempty"`
	// Optional message providing additional context
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessCheckResponse) Reset() {
	*x = ReadinessCheckResponse{}
	mi := &file_v1_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessCheckResponse) ProtoMessage() {}

func (x *ReadinessCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessCheckResponse.ProtoReflect.Descriptor instead.
func (*ReadinessCheckResponse) Descriptor() ([]byte, []int) {
	return file_v1_health_proto_rawDescGZIP(), []int{3}
}

func (x *ReadinessCheckResponse) GetStatus() ReadinessStatus {
	if x != nil {
		return x.Status
	}
	return ReadinessStatus_READINESS_STATUS_UNSPECIFIED
}

func (x *ReadinessCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_health_proto protoreflect.FileDescriptor

const file_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/health.proto\x12\n" +
	"netctrl.v1\x1a\x1cgoogle/api/annotations.proto\"\x14\n" +
	"\x12HealthCheckRequest\"a\n" +
	"\x13HealthCheckResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.netctrl.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x17\n" +
	"\x15ReadinessCheckRequest\"g\n" +
	"\x16ReadinessCheckResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.netctrl.v1.ReadinessStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*e\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x02*o\n" +
	"\x0fReadinessStatus\x12 \n" +
	"\x1cREADINESS_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16READINESS_STATUS_READY\x10\x01\x12\x1e\n" +
	"\x1aREADINESS_STATUS_NOT_READY\x10\x022\xd8\x01\n" +
	"\rHealthService\x12`\n" +
	"\x05Check\x12\x1e.netctrl.v1.HealthCheckRequest\x1a\x1f.netctrl.v1.HealthCheckResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/health\x12e\n" +
	"\x05Ready\x12!.netctrl.v1.ReadinessCheckRequest\x1a\".netctrl.v1.ReadinessCheckResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/readyB\x9e\x01\n" +
	"\x0ecom.netctrl.v1B\vHealthProtoP\x01Z6github.com/filanov/netctrl-server/pkg/api/v1;netctrlv1\xa2\x02\x03NXX\xaa\x02\n" +
	"Netctrl.V1\xca\x02\n" +
	"Netctrl\\V1\xe2\x02\x16Netctrl\\V1\\GPBMetadata\xea\x02\vNetctrl::V1b\x06proto3"

var (
	file_v1_health_proto_rawDescOnce sync.Once
	file_v1_health_proto_rawDescData []byte
)

func file_v1_health_proto_rawDescGZIP() []byte {
	file_v1_health_proto_rawDescOnce.Do(func() {
		file_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_health_proto_rawDesc), len(file_v1_health_proto_rawDesc)))
	})
	return file_v1_health_proto_rawDescData
}

var file_v1_health_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_health_proto_goTypes = []any{
	(HealthStatus)(0),              // 0: netctrl.v1.HealthStatus
	(ReadinessStatus)(0),           // 1: netctrl.v1.ReadinessStatus
	(*HealthCheckRequest)(nil),     // 2: netctrl.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 3: netctrl.v1.HealthCheckResponse
	(*ReadinessCheckRequest)(nil),  // 4: netctrl.v1.ReadinessCheckRequest
	(*ReadinessCheckResponse)(nil), // 5: netctrl.v1.ReadinessCheckResponse
}
var file_v1_health_proto_depIdxs = []int32{
	0, // 0: netctrl.v1.HealthCheckResponse.status:type_name -> netctrl.v1.HealthStatus
	1, // 1: netctrl.v1.ReadinessCheckResponse.status:type_name -> netctrl.v1.ReadinessStatus
	2, // 2: netctrl.v1.HealthService.Check:input_type -> netctrl.v1.HealthCheckRequest
	4, // 3: netctrl.v1.HealthService.Ready:input_type -> netctrl.v1.ReadinessCheckRequest
	3, // 4: netctrl.v1.HealthService.Check:output_type -> netctrl.v1.HealthCheckResponse
	5, // 5: netctrl.v1.HealthService.Ready:output_type -> netctrl.v1.ReadinessCheckResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_health_proto_init() }
func file_v1_health_proto_init() {
	if File_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_health_proto_rawDesc), len(file_v1_health_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_health_proto_goTypes,
		DependencyIndexes: file_v1_health_proto_depIdxs,
		EnumInfos:         file_v1_health_proto_enumTypes,
		MessageInfos:      file_v1_health_proto_msgTypes,
	}.Build()
	File_v1_health_proto = out.File
	file_v1_health_proto_goTypes = nil
	file_v1_health_proto_depIdxs = nil
}
